<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260406152437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE critere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organe VARCHAR(255) NOT NULL, description TEXT NOT NULL, plante_id BIGINT DEFAULT NULL, source_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7F6A8053177B16E8 ON critere (plante_id)');
        $this->addSql('CREATE INDEX IDX_7F6A8053953C1C61 ON critere (source_id)');
        $this->addSql('CREATE TABLE image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chemin VARCHAR(255) NOT NULL, auteur VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, critere_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C53D045F9E5F45AB ON image (critere_id)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, auteur VARCHAR(255) DEFAULT NULL, annee INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE taxref (cd_nom BIGINT NOT NULL, cd_ref BIGINT NOT NULL, famille VARCHAR(255) NOT NULL, nom_complet_html VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (cd_nom))');
        $this->addSql('CREATE INDEX IDX_C086DF4B2B50F59F ON taxref (cd_ref)');
        $this->addSql('ALTER TABLE critere ADD CONSTRAINT FK_7F6A8053177B16E8 FOREIGN KEY (plante_id) REFERENCES taxref (cd_nom) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE critere ADD CONSTRAINT FK_7F6A8053953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F9E5F45AB FOREIGN KEY (critere_id) REFERENCES critere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxref ADD CONSTRAINT FK_C086DF4B2B50F59F FOREIGN KEY (cd_ref) REFERENCES taxref (cd_nom) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE critere DROP CONSTRAINT FK_7F6A8053177B16E8');
        $this->addSql('ALTER TABLE critere DROP CONSTRAINT FK_7F6A8053953C1C61');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F9E5F45AB');
        $this->addSql('ALTER TABLE taxref DROP CONSTRAINT FK_C086DF4B2B50F59F');
        $this->addSql('DROP TABLE critere');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE taxref');
    }
}
