<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407131840 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE observation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE observation_critere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, valeur BOOLEAN NOT NULL, observation_id INT NOT NULL, critere_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DDB89A871409DD88 ON observation_critere (observation_id)');
        $this->addSql('CREATE INDEX IDX_DDB89A879E5F45AB ON observation_critere (critere_id)');
        $this->addSql('ALTER TABLE observation_critere ADD CONSTRAINT FK_DDB89A871409DD88 FOREIGN KEY (observation_id) REFERENCES observation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE observation_critere ADD CONSTRAINT FK_DDB89A879E5F45AB FOREIGN KEY (critere_id) REFERENCES critere (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE observation_critere DROP CONSTRAINT FK_DDB89A871409DD88');
        $this->addSql('ALTER TABLE observation_critere DROP CONSTRAINT FK_DDB89A879E5F45AB');
        $this->addSql('DROP TABLE observation');
        $this->addSql('DROP TABLE observation_critere');
    }
}
