<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411100606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE statut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE observation ALTER date_heure DROP NOT NULL');
        $this->addSql('ALTER TABLE observation_critere ADD statut_id INT NOT NULL');
        $this->addSql('ALTER TABLE observation_critere DROP valeur');
        $this->addSql('ALTER TABLE observation_critere ADD CONSTRAINT FK_DDB89A87F6203804 FOREIGN KEY (statut_id) REFERENCES statut (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_DDB89A87F6203804 ON observation_critere (statut_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE statut');
        $this->addSql('ALTER TABLE observation ALTER date_heure SET NOT NULL');
        $this->addSql('ALTER TABLE observation_critere DROP CONSTRAINT FK_DDB89A87F6203804');
        $this->addSql('DROP INDEX IDX_DDB89A87F6203804');
        $this->addSql('ALTER TABLE observation_critere ADD valeur BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE observation_critere DROP statut_id');
    }
}
